#####使用哪个环境 prod生成环境  dev开发环境########
spring:
  profiles:
    active: dev
########## JPA配置 ##########   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
######### 静态资源访问配置 ###########
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
########  开启模板热部署 ##########
  thymeleaf:
    cache: false 
    
########## 文件上传配置 #########
  servlet:
    multipart:
      enabled: true # 开启多文件上传
      max-file-size: 5MB 
      max-request-size: 5MB

######## mybatis配置 #############
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.pibigstar.domain # 实体扫描路径
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名   

#### 文件上传目录配置 ####

file:
  path: E://temp/
