#####使用哪个环境 prod生成环境  dev开发环境########
spring:
  profiles:
    active: dev
########## JPA配置 ##########   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
########## 静态资源访问配置 ###########
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

  thymeleaf:
    cache: false #开启模板热部署
######## mybatis配置 #############
mybatis:
  #config-location:  classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  

